[package]
name = "pid-simulator"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.0"

[dependencies]
color-eyre = "0.6"
crossterm = "0.29"
ratatui = {version = "0.30.0-alpha.5", features = ["crossterm"]}
